name: Go
on:
  push:
    paths:
    - '*'        # Run workflow for all file paths
    - '!/build/*' # Don't run workflow when files are only in the /docs directory
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13.4
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
      id: go

    - name: Check out code into the Go module directory
      env:
        advice.detachedHead: false
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
      run: |
        git checkout master
        env GOOS=linux GOARCH=amd64 go build -o build/linux_amd64.run loanPay.go
        env GOOS=windows GOARCH=amd64 go build -o build/windows_amd64.exe loanPay.go
        chmod +x build/linux_amd64.run
        chmod +x build/windows_amd64.exe
        git config --global user.email "$GITHUB_EMAIL"
        git config --global user.name "Github Actions"
        git add .
        git commit -m "New build"
        git remote set-url origin https://${{GITHUB_ACTOR}}:$GITHUB_TOKEN@github.com/${{GITHUB_REPOSITORY}}.git
        git push origin master